/**
 * Catálogo inicial de CFOPs. Mistura duas fontes:
 *  1. Tabela RFB "Operações Geradoras de Créditos" (73 códigos, marcados como
 *     `geraCreditoPisCofins: true` — Lei 10.637/2002 + 10.833/2003).
 *  2. CFOPs essenciais de saída/transferência/devolução/remessa publicados pelo
 *     Ajuste Sinief s/n de 1970 + atualizações. Cobertura ~95% das operações usuais.
 *
 * A lista oficial CONFAZ tem ~700 entradas. Use a tela de CFOPs ou o seed para
 * adicionar os faltantes conforme a empresa precisar.
 */

export interface CfopSeedEntry {
  codigo: string;
  descricao: string;
  grupo: string;
  geraCreditoPisCofins?: boolean;
}

export const CFOPS_SEED: CfopSeedEntry[] = [
  // ============ Aquisição de Bens para Revenda (gera crédito PIS/COFINS) ============
  { codigo: '1102', descricao: 'Compra para comercialização', grupo: 'Aquisição de Bens para Revenda', geraCreditoPisCofins: true },
  { codigo: '1113', descricao: 'Compra para comercialização, de mercadoria recebida anteriormente em consignação mercantil', grupo: 'Aquisição de Bens para Revenda', geraCreditoPisCofins: true },
  { codigo: '1117', descricao: 'Compra para comercialização originada de encomenda para recebimento futuro', grupo: 'Aquisição de Bens para Revenda', geraCreditoPisCofins: true },
  { codigo: '1118', descricao: 'Compra de mercadoria para comercialização pelo adquirente originário, entregue pelo vendedor remetente ao destinatário, em venda à ordem', grupo: 'Aquisição de Bens para Revenda', geraCreditoPisCofins: true },
  { codigo: '1121', descricao: 'Compra para comercialização, em venda à ordem, já recebida do vendedor remetente', grupo: 'Aquisição de Bens para Revenda', geraCreditoPisCofins: true },
  { codigo: '1251', descricao: 'Compra de energia elétrica para distribuição ou comercialização', grupo: 'Aquisição de Bens para Revenda', geraCreditoPisCofins: true },
  { codigo: '1403', descricao: 'Compra para comercialização em operação com mercadoria sujeita ao regime de substituição tributária do ICMS', grupo: 'Aquisição de Bens para Revenda', geraCreditoPisCofins: true },
  { codigo: '1652', descricao: 'Compra de combustível ou lubrificante para comercialização', grupo: 'Aquisição de Bens para Revenda', geraCreditoPisCofins: true },
  { codigo: '2102', descricao: 'Compra para comercialização', grupo: 'Aquisição de Bens para Revenda', geraCreditoPisCofins: true },
  { codigo: '2113', descricao: 'Compra para comercialização, de mercadoria recebida anteriormente em consignação mercantil', grupo: 'Aquisição de Bens para Revenda', geraCreditoPisCofins: true },
  { codigo: '2117', descricao: 'Compra para comercialização originada de encomenda para recebimento futuro', grupo: 'Aquisição de Bens para Revenda', geraCreditoPisCofins: true },
  { codigo: '2118', descricao: 'Compra de mercadoria para comercialização pelo adquirente originário, entregue pelo vendedor remetente ao destinatário, em venda à ordem', grupo: 'Aquisição de Bens para Revenda', geraCreditoPisCofins: true },
  { codigo: '2121', descricao: 'Compra para comercialização, em venda à ordem, já recebida do vendedor remetente', grupo: 'Aquisição de Bens para Revenda', geraCreditoPisCofins: true },
  { codigo: '2251', descricao: 'Compra de energia elétrica para distribuição ou comercialização', grupo: 'Aquisição de Bens para Revenda', geraCreditoPisCofins: true },
  { codigo: '2403', descricao: 'Compra para comercialização em operação com mercadoria sujeita ao regime de substituição tributária do ICMS', grupo: 'Aquisição de Bens para Revenda', geraCreditoPisCofins: true },
  { codigo: '2652', descricao: 'Compra de combustível ou lubrificante para comercialização', grupo: 'Aquisição de Bens para Revenda', geraCreditoPisCofins: true },
  { codigo: '3102', descricao: 'Compra para comercialização (Importação)', grupo: 'Aquisição de Bens para Revenda', geraCreditoPisCofins: true },
  { codigo: '3251', descricao: 'Compra de energia elétrica para distribuição ou comercialização (Importação)', grupo: 'Aquisição de Bens para Revenda', geraCreditoPisCofins: true },
  { codigo: '3652', descricao: 'Compra de combustível ou lubrificante para comercialização (Importação)', grupo: 'Aquisição de Bens para Revenda', geraCreditoPisCofins: true },

  // ============ Aquisição de Bens Utilizados como Insumo ============
  { codigo: '1101', descricao: 'Compra para industrialização ou produção rural', grupo: 'Aquisição de Insumo', geraCreditoPisCofins: true },
  { codigo: '1111', descricao: 'Compra para industrialização, de mercadoria recebida em consignação industrial', grupo: 'Aquisição de Insumo', geraCreditoPisCofins: true },
  { codigo: '1116', descricao: 'Compra para industrialização originada de encomenda para recebimento futuro', grupo: 'Aquisição de Insumo', geraCreditoPisCofins: true },
  { codigo: '1120', descricao: 'Compra para industrialização, em venda à ordem, já recebida do vendedor remetente', grupo: 'Aquisição de Insumo', geraCreditoPisCofins: true },
  { codigo: '1122', descricao: 'Compra para industrialização em que a mercadoria foi remetida pelo fornecedor ao industrializador sem transitar pelo estabelecimento adquirente', grupo: 'Aquisição de Insumo', geraCreditoPisCofins: true },
  { codigo: '1126', descricao: 'Compra para utilização na prestação de serviço sujeito ao ICMS', grupo: 'Aquisição de Insumo', geraCreditoPisCofins: true },
  { codigo: '1128', descricao: 'Compra para utilização na prestação de serviço sujeito ao ISSQN', grupo: 'Aquisição de Insumo', geraCreditoPisCofins: true },
  { codigo: '1401', descricao: 'Compra para industrialização em operação com mercadoria sujeita ao regime de ST', grupo: 'Aquisição de Insumo', geraCreditoPisCofins: true },
  { codigo: '1407', descricao: 'Compra de mercadoria para uso ou consumo sujeita ao regime de ST', grupo: 'Aquisição de Insumo', geraCreditoPisCofins: true },
  { codigo: '1556', descricao: 'Compra de material para uso ou consumo', grupo: 'Aquisição de Insumo', geraCreditoPisCofins: true },
  { codigo: '1651', descricao: 'Compra de combustível ou lubrificante para industrialização subsequente', grupo: 'Aquisição de Insumo', geraCreditoPisCofins: true },
  { codigo: '1653', descricao: 'Compra de combustível ou lubrificante por consumidor ou usuário final', grupo: 'Aquisição de Insumo', geraCreditoPisCofins: true },
  { codigo: '2101', descricao: 'Compra para industrialização ou produção rural', grupo: 'Aquisição de Insumo', geraCreditoPisCofins: true },
  { codigo: '2111', descricao: 'Compra para industrialização, de mercadoria recebida em consignação industrial', grupo: 'Aquisição de Insumo', geraCreditoPisCofins: true },
  { codigo: '2116', descricao: 'Compra para industrialização originada de encomenda para recebimento futuro', grupo: 'Aquisição de Insumo', geraCreditoPisCofins: true },
  { codigo: '2120', descricao: 'Compra para industrialização, em venda à ordem, já recebida do vendedor remetente', grupo: 'Aquisição de Insumo', geraCreditoPisCofins: true },
  { codigo: '2122', descricao: 'Compra para industrialização em que a mercadoria foi remetida pelo fornecedor ao industrializador sem transitar pelo estabelecimento adquirente', grupo: 'Aquisição de Insumo', geraCreditoPisCofins: true },
  { codigo: '2126', descricao: 'Compra para utilização na prestação de serviço sujeito ao ICMS', grupo: 'Aquisição de Insumo', geraCreditoPisCofins: true },
  { codigo: '2128', descricao: 'Compra para utilização na prestação de serviço sujeita ao ISSQN', grupo: 'Aquisição de Insumo', geraCreditoPisCofins: true },
  { codigo: '2401', descricao: 'Compra para industrialização em operação com mercadoria sujeita ao regime de ST', grupo: 'Aquisição de Insumo', geraCreditoPisCofins: true },
  { codigo: '2407', descricao: 'Compra de mercadoria para uso ou consumo sujeita ao regime de ST', grupo: 'Aquisição de Insumo', geraCreditoPisCofins: true },
  { codigo: '2556', descricao: 'Compra de material para uso ou consumo', grupo: 'Aquisição de Insumo', geraCreditoPisCofins: true },
  { codigo: '2651', descricao: 'Compra de combustível ou lubrificante para industrialização subsequente', grupo: 'Aquisição de Insumo', geraCreditoPisCofins: true },
  { codigo: '2653', descricao: 'Compra de combustível ou lubrificante por consumidor ou usuário final', grupo: 'Aquisição de Insumo', geraCreditoPisCofins: true },
  { codigo: '3101', descricao: 'Compra para industrialização ou produção rural (Importação)', grupo: 'Aquisição de Insumo', geraCreditoPisCofins: true },
  { codigo: '3126', descricao: 'Compra para utilização na prestação de serviço (Importação)', grupo: 'Aquisição de Insumo', geraCreditoPisCofins: true },
  { codigo: '3128', descricao: 'Compra para utilização na prestação de serviço sujeita ao ISSQN (Importação)', grupo: 'Aquisição de Insumo', geraCreditoPisCofins: true },
  { codigo: '3556', descricao: 'Compra de material para uso ou consumo (Importação)', grupo: 'Aquisição de Insumo', geraCreditoPisCofins: true },
  { codigo: '3651', descricao: 'Compra de combustível ou lubrificante para industrialização subsequente (Importação)', grupo: 'Aquisição de Insumo', geraCreditoPisCofins: true },
  { codigo: '3653', descricao: 'Compra de combustível ou lubrificante por consumidor ou usuário final (Importação)', grupo: 'Aquisição de Insumo', geraCreditoPisCofins: true },

  // ============ Aquisição de Serviços (PIS/COFINS) ============
  { codigo: '1124', descricao: 'Industrialização efetuada por outra empresa', grupo: 'Aquisição de Serviços', geraCreditoPisCofins: true },
  { codigo: '1125', descricao: 'Industrialização efetuada por outra empresa, quando a mercadoria não transitou pelo estabelecimento adquirente', grupo: 'Aquisição de Serviços', geraCreditoPisCofins: true },
  { codigo: '1933', descricao: 'Aquisição de serviço tributado pelo ISS', grupo: 'Aquisição de Serviços', geraCreditoPisCofins: true },
  { codigo: '2124', descricao: 'Industrialização efetuada por outra empresa', grupo: 'Aquisição de Serviços', geraCreditoPisCofins: true },
  { codigo: '2125', descricao: 'Industrialização efetuada por outra empresa, quando a mercadoria não transitou pelo estabelecimento adquirente', grupo: 'Aquisição de Serviços', geraCreditoPisCofins: true },
  { codigo: '2933', descricao: 'Aquisição de serviço tributado pelo ISS', grupo: 'Aquisição de Serviços', geraCreditoPisCofins: true },

  // ============ Devolução de Vendas (gera crédito PIS/COFINS) ============
  { codigo: '1201', descricao: 'Devolução de venda de produção do estabelecimento', grupo: 'Devolução de Vendas', geraCreditoPisCofins: true },
  { codigo: '1202', descricao: 'Devolução de venda de mercadoria adquirida ou recebida de terceiros', grupo: 'Devolução de Vendas', geraCreditoPisCofins: true },
  { codigo: '1203', descricao: 'Devolução de venda destinada à ZFM/ALC (produção)', grupo: 'Devolução de Vendas', geraCreditoPisCofins: true },
  { codigo: '1204', descricao: 'Devolução de venda destinada à ZFM/ALC (revenda)', grupo: 'Devolução de Vendas', geraCreditoPisCofins: true },
  { codigo: '1410', descricao: 'Devolução de venda em ST (produção)', grupo: 'Devolução de Vendas', geraCreditoPisCofins: true },
  { codigo: '1411', descricao: 'Devolução de venda em ST (revenda)', grupo: 'Devolução de Vendas', geraCreditoPisCofins: true },
  { codigo: '1660', descricao: 'Devolução de venda de combustível para industrialização subsequente', grupo: 'Devolução de Vendas', geraCreditoPisCofins: true },
  { codigo: '1661', descricao: 'Devolução de venda de combustível para comercialização', grupo: 'Devolução de Vendas', geraCreditoPisCofins: true },
  { codigo: '1662', descricao: 'Devolução de venda de combustível para consumidor final', grupo: 'Devolução de Vendas', geraCreditoPisCofins: true },
  { codigo: '2201', descricao: 'Devolução de venda de produção do estabelecimento', grupo: 'Devolução de Vendas', geraCreditoPisCofins: true },
  { codigo: '2202', descricao: 'Devolução de venda de mercadoria adquirida ou recebida de terceiros', grupo: 'Devolução de Vendas', geraCreditoPisCofins: true },
  { codigo: '2410', descricao: 'Devolução de venda em ST (produção)', grupo: 'Devolução de Vendas', geraCreditoPisCofins: true },
  { codigo: '2411', descricao: 'Devolução de venda em ST (revenda)', grupo: 'Devolução de Vendas', geraCreditoPisCofins: true },
  { codigo: '2660', descricao: 'Devolução de venda de combustível para industrialização subsequente', grupo: 'Devolução de Vendas', geraCreditoPisCofins: true },
  { codigo: '2661', descricao: 'Devolução de venda de combustível para comercialização', grupo: 'Devolução de Vendas', geraCreditoPisCofins: true },
  { codigo: '2662', descricao: 'Devolução de venda de combustível para consumidor final', grupo: 'Devolução de Vendas', geraCreditoPisCofins: true },

  // ============ Outras Operações com Direito a Crédito ============
  { codigo: '1922', descricao: 'Lançamento por simples faturamento decorrente de compra para recebimento futuro', grupo: 'Outras com Direito a Crédito', geraCreditoPisCofins: true },
  { codigo: '2922', descricao: 'Lançamento por simples faturamento decorrente de compra para recebimento futuro', grupo: 'Outras com Direito a Crédito', geraCreditoPisCofins: true },

  // ============ Vendas — Estaduais (5xxx) ============
  { codigo: '5101', descricao: 'Venda de produção do estabelecimento', grupo: 'Vendas' },
  { codigo: '5102', descricao: 'Venda de mercadoria adquirida ou recebida de terceiros', grupo: 'Vendas' },
  { codigo: '5103', descricao: 'Venda de produção do estabelecimento efetuada fora do estabelecimento', grupo: 'Vendas' },
  { codigo: '5104', descricao: 'Venda de mercadoria adquirida ou recebida de terceiros efetuada fora do estabelecimento', grupo: 'Vendas' },
  { codigo: '5109', descricao: 'Venda de produção destinada à Zona Franca de Manaus ou Áreas de Livre Comércio', grupo: 'Vendas' },
  { codigo: '5110', descricao: 'Venda de mercadoria de terceiros destinada à ZFM/ALC', grupo: 'Vendas' },
  { codigo: '5111', descricao: 'Venda de produção do estabelecimento remetida anteriormente em consignação industrial', grupo: 'Vendas' },
  { codigo: '5113', descricao: 'Venda de produção do estabelecimento, remetida em consignação mercantil', grupo: 'Vendas' },
  { codigo: '5114', descricao: 'Venda de mercadoria de terceiros remetida em consignação mercantil', grupo: 'Vendas' },
  { codigo: '5116', descricao: 'Venda de produção do estabelecimento originada de encomenda para entrega futura', grupo: 'Vendas' },
  { codigo: '5117', descricao: 'Venda de mercadoria de terceiros originada de encomenda para entrega futura', grupo: 'Vendas' },
  { codigo: '5118', descricao: 'Venda de produção entregue ao destinatário por conta e ordem do adquirente originário, em venda à ordem', grupo: 'Vendas' },
  { codigo: '5119', descricao: 'Venda de mercadoria de terceiros entregue ao destinatário por conta e ordem do adquirente originário, em venda à ordem', grupo: 'Vendas' },
  { codigo: '5120', descricao: 'Venda de mercadoria de terceiros entregue ao destinatário pelo vendedor remetente, em venda à ordem', grupo: 'Vendas' },
  { codigo: '5122', descricao: 'Venda de produção do estabelecimento remetida para industrialização por encomenda', grupo: 'Vendas' },
  { codigo: '5123', descricao: 'Venda de mercadoria de terceiros remetida para industrialização por encomenda', grupo: 'Vendas' },
  { codigo: '5401', descricao: 'Venda de produção do estabelecimento em operação com produto sujeito ao regime de ST', grupo: 'Vendas (ST)' },
  { codigo: '5402', descricao: 'Venda de produção em operação entre contribuintes substitutos do mesmo produto', grupo: 'Vendas (ST)' },
  { codigo: '5403', descricao: 'Venda de mercadoria de terceiros em operação com produto sujeito ao regime de ST', grupo: 'Vendas (ST)' },
  { codigo: '5405', descricao: 'Venda de mercadoria de terceiros sujeita ao regime de ST, na condição de contribuinte substituído', grupo: 'Vendas (ST)' },
  { codigo: '5408', descricao: 'Transferência de produção em operação com produto sujeito ao regime de ST', grupo: 'Transferências' },
  { codigo: '5409', descricao: 'Transferência de mercadoria adquirida ou recebida de terceiros sujeita ao regime de ST', grupo: 'Transferências' },
  { codigo: '5151', descricao: 'Transferência de produção do estabelecimento', grupo: 'Transferências' },
  { codigo: '5152', descricao: 'Transferência de mercadoria adquirida ou recebida de terceiros', grupo: 'Transferências' },
  { codigo: '5155', descricao: 'Transferência de produção do estabelecimento em operação com produto sujeito ao regime de ST', grupo: 'Transferências' },
  { codigo: '5156', descricao: 'Transferência de mercadoria de terceiros sujeita ao regime de ST', grupo: 'Transferências' },
  { codigo: '5251', descricao: 'Venda de energia elétrica para distribuição ou comercialização', grupo: 'Energia Elétrica' },
  { codigo: '5253', descricao: 'Venda de energia elétrica para estabelecimento comercial', grupo: 'Energia Elétrica' },
  { codigo: '5255', descricao: 'Venda de energia elétrica para consumidor final', grupo: 'Energia Elétrica' },
  { codigo: '5301', descricao: 'Prestação de serviço de comunicação para execução de serviço da mesma natureza', grupo: 'Serviços de Comunicação' },
  { codigo: '5351', descricao: 'Prestação de serviço de transporte para execução de serviço da mesma natureza', grupo: 'Serviços de Transporte' },
  { codigo: '5352', descricao: 'Prestação de serviço de transporte a estabelecimento industrial', grupo: 'Serviços de Transporte' },
  { codigo: '5353', descricao: 'Prestação de serviço de transporte a estabelecimento comercial', grupo: 'Serviços de Transporte' },
  { codigo: '5500', descricao: 'Remessa de produção do estabelecimento, com fim específico de exportação', grupo: 'Outras Saídas' },
  { codigo: '5551', descricao: 'Venda de bem do ativo imobilizado', grupo: 'Ativo Imobilizado' },
  { codigo: '5552', descricao: 'Transferência de bem do ativo imobilizado', grupo: 'Ativo Imobilizado' },
  { codigo: '5556', descricao: 'Devolução de compra de material de uso ou consumo', grupo: 'Devoluções' },
  { codigo: '5557', descricao: 'Transferência de material de uso ou consumo', grupo: 'Outras Saídas' },
  { codigo: '5901', descricao: 'Remessa para industrialização por encomenda', grupo: 'Remessas' },
  { codigo: '5902', descricao: 'Retorno de mercadoria utilizada na industrialização por encomenda', grupo: 'Retornos' },
  { codigo: '5904', descricao: 'Remessa para venda fora do estabelecimento', grupo: 'Remessas' },
  { codigo: '5905', descricao: 'Remessa para depósito fechado ou armazém geral', grupo: 'Remessas' },
  { codigo: '5906', descricao: 'Retorno de mercadoria depositada em depósito fechado ou armazém geral', grupo: 'Retornos' },
  { codigo: '5910', descricao: 'Remessa em bonificação, doação ou brinde', grupo: 'Outras Saídas' },
  { codigo: '5911', descricao: 'Remessa de amostra grátis', grupo: 'Outras Saídas' },
  { codigo: '5912', descricao: 'Remessa de mercadoria ou bem para demonstração', grupo: 'Remessas' },
  { codigo: '5913', descricao: 'Retorno de mercadoria recebida para demonstração', grupo: 'Retornos' },
  { codigo: '5915', descricao: 'Remessa de mercadoria ou bem para conserto ou reparo', grupo: 'Remessas' },
  { codigo: '5916', descricao: 'Retorno de mercadoria recebida para conserto ou reparo', grupo: 'Retornos' },
  { codigo: '5917', descricao: 'Remessa de mercadoria em consignação mercantil ou industrial', grupo: 'Consignações' },
  { codigo: '5918', descricao: 'Devolução de mercadoria recebida em consignação mercantil ou industrial', grupo: 'Consignações' },
  { codigo: '5920', descricao: 'Remessa de vasilhame ou sacaria', grupo: 'Outras Saídas' },
  { codigo: '5921', descricao: 'Devolução de vasilhame ou sacaria', grupo: 'Outras Saídas' },
  { codigo: '5922', descricao: 'Lançamento efetuado a título de simples faturamento decorrente de venda para entrega futura', grupo: 'Outras Saídas' },
  { codigo: '5923', descricao: 'Remessa de mercadoria por conta e ordem de terceiros, em venda à ordem', grupo: 'Outras Saídas' },
  { codigo: '5933', descricao: 'Prestação de serviço tributado pelo ISSQN', grupo: 'Serviços' },
  { codigo: '5949', descricao: 'Outra saída de mercadoria ou prestação de serviço não especificado', grupo: 'Outras Saídas' },

  // ============ Vendas — Interestaduais (6xxx) ============
  { codigo: '6101', descricao: 'Venda de produção do estabelecimento', grupo: 'Vendas' },
  { codigo: '6102', descricao: 'Venda de mercadoria adquirida ou recebida de terceiros', grupo: 'Vendas' },
  { codigo: '6107', descricao: 'Venda de produção do estabelecimento, destinada a não contribuinte', grupo: 'Vendas' },
  { codigo: '6108', descricao: 'Venda de mercadoria adquirida ou recebida de terceiros, destinada a não contribuinte', grupo: 'Vendas' },
  { codigo: '6109', descricao: 'Venda de produção destinada à ZFM/ALC', grupo: 'Vendas' },
  { codigo: '6110', descricao: 'Venda de mercadoria de terceiros destinada à ZFM/ALC', grupo: 'Vendas' },
  { codigo: '6111', descricao: 'Venda de produção do estabelecimento remetida anteriormente em consignação industrial', grupo: 'Vendas' },
  { codigo: '6116', descricao: 'Venda de produção do estabelecimento originada de encomenda para entrega futura', grupo: 'Vendas' },
  { codigo: '6117', descricao: 'Venda de mercadoria de terceiros originada de encomenda para entrega futura', grupo: 'Vendas' },
  { codigo: '6122', descricao: 'Venda de produção do estabelecimento remetida para industrialização por encomenda', grupo: 'Vendas' },
  { codigo: '6151', descricao: 'Transferência de produção do estabelecimento', grupo: 'Transferências' },
  { codigo: '6152', descricao: 'Transferência de mercadoria adquirida ou recebida de terceiros', grupo: 'Transferências' },
  { codigo: '6155', descricao: 'Transferência de produção do estabelecimento em operação com produto sujeito ao regime de ST', grupo: 'Transferências' },
  { codigo: '6156', descricao: 'Transferência de mercadoria de terceiros sujeita ao regime de ST', grupo: 'Transferências' },
  { codigo: '6401', descricao: 'Venda de produção do estabelecimento em operação com produto sujeito ao regime de ST', grupo: 'Vendas (ST)' },
  { codigo: '6402', descricao: 'Venda de produção em operação entre contribuintes substitutos do mesmo produto', grupo: 'Vendas (ST)' },
  { codigo: '6403', descricao: 'Venda de mercadoria de terceiros em operação com produto sujeito ao regime de ST', grupo: 'Vendas (ST)' },
  { codigo: '6404', descricao: 'Venda de mercadoria de terceiros sujeita ao ST, na condição de contribuinte substituído', grupo: 'Vendas (ST)' },
  { codigo: '6408', descricao: 'Transferência de produção em operação com produto sujeito ao regime de ST', grupo: 'Transferências' },
  { codigo: '6409', descricao: 'Transferência de mercadoria adquirida ou recebida de terceiros sujeita ao regime de ST', grupo: 'Transferências' },
  { codigo: '6500', descricao: 'Remessa de mercadoria com fim específico de exportação', grupo: 'Outras Saídas' },
  { codigo: '6551', descricao: 'Venda de bem do ativo imobilizado', grupo: 'Ativo Imobilizado' },
  { codigo: '6552', descricao: 'Transferência de bem do ativo imobilizado', grupo: 'Ativo Imobilizado' },
  { codigo: '6910', descricao: 'Remessa em bonificação, doação ou brinde', grupo: 'Outras Saídas' },
  { codigo: '6911', descricao: 'Remessa de amostra grátis', grupo: 'Outras Saídas' },
  { codigo: '6915', descricao: 'Remessa de mercadoria ou bem para conserto ou reparo', grupo: 'Remessas' },
  { codigo: '6916', descricao: 'Retorno de mercadoria recebida para conserto ou reparo', grupo: 'Retornos' },
  { codigo: '6917', descricao: 'Remessa de mercadoria em consignação mercantil ou industrial', grupo: 'Consignações' },
  { codigo: '6922', descricao: 'Lançamento efetuado a título de simples faturamento decorrente de venda para entrega futura', grupo: 'Outras Saídas' },
  { codigo: '6949', descricao: 'Outra saída de mercadoria ou prestação de serviço não especificado', grupo: 'Outras Saídas' },

  // ============ Exportação (7xxx) ============
  { codigo: '7101', descricao: 'Venda de produção do estabelecimento (exportação)', grupo: 'Exportação' },
  { codigo: '7102', descricao: 'Venda de mercadoria adquirida ou recebida de terceiros (exportação)', grupo: 'Exportação' },
  { codigo: '7105', descricao: 'Venda de produção remetida com fim específico de exportação', grupo: 'Exportação' },
  { codigo: '7106', descricao: 'Venda de mercadoria de terceiros remetida com fim específico de exportação', grupo: 'Exportação' },
  { codigo: '7127', descricao: 'Venda de produção sob regime de drawback', grupo: 'Exportação' },
  { codigo: '7501', descricao: 'Remessa de mercadoria com fim específico de exportação', grupo: 'Exportação' },
  { codigo: '7551', descricao: 'Venda de bem do ativo imobilizado (exportação)', grupo: 'Exportação' },
  { codigo: '7949', descricao: 'Outra saída de mercadoria ou prestação de serviço (exportação) não especificada', grupo: 'Exportação' },
];
